name: ud_design
description: A Flutter package to develop responsive flutter applications.
version: 0.0.1
homepage: https://github.com/shajedulislam/ud_design

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
